import React, { useMemo, useState } from 'react';
import { Bell, CalendarClock, Check, Clock3, Plus, X } from 'lucide-react';
import { customerActivities as initialActivities, type CustomerActivity, type Priority } from '../types/data';
import { ActivityIcon, PageHeader, PortalNav, SearchBox, StatCard, portalStatus, priorityBadge } from '../components/PortalUi';

export const CustomerActivitiesPage: React.FC = () => {
 const [activities,setActivities]=useState<CustomerActivity[]>(initialActivities); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const [showCreate,setShowCreate]=useState(false); const [notice,setNotice]=useState('');
 const [form,setForm]=useState({activityType:'Call' as CustomerActivity['activityType'],subject:'',description:'',relatedContact:'Rohan Mehta',relatedOpportunity:'—',activityDate:'',owner:'Priya Nair',status:'Planned' as CustomerActivity['status'],priority:'Medium' as Priority,nextAction:'',reminderDate:''});
 const rows=useMemo(()=>activities.filter(a=>`${a.id} ${a.activityType} ${a.subject} ${a.owner} ${a.relatedContact}`.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||a.status===filter)),[activities,query,filter]);
 const create=(e:React.FormEvent)=>{e.preventDefault();if(!form.subject.trim()||!form.description.trim())return;const activity:CustomerActivity={...form,id:`ACT-${2202+activities.length}`,activityDate:form.activityDate||'Sep 29, 2026 · 03:00 PM',reminderDate:form.reminderDate||'—'};setActivities([activity,...activities]);setShowCreate(false);setForm({...form,subject:'',description:'',nextAction:'',reminderDate:''});setNotice(`${activity.id} created successfully.`);window.setTimeout(()=>setNotice(''),2500)};
 return <div className="p-5 md:p-7"><PageHeader title="Customer Activities" description="Review customer interactions, follow-ups, owners and reminders." action={<button onClick={()=>setShowCreate(true)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/> Log Activity</button>}/><PortalNav/>{notice&&<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{notice}</div>}
 <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3"><StatCard label="Total Activities" value={activities.length} icon={<Bell size={19}/>}/><StatCard label="Pending / Planned" value={activities.filter(a=>a.status!=='Completed').length} icon={<Clock3 size={19}/>} tone="bg-amber-50 text-amber-600"/><StatCard label="With Reminders" value={activities.filter(a=>a.reminderDate!=='—').length} icon={<CalendarClock size={19}/>} tone="bg-violet-50 text-violet-600"/></div>
 <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row"><div className="flex-1"><SearchBox value={query} onChange={setQuery} placeholder="Search activity, contact, owner..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option>All</option><option>Planned</option><option>Completed</option><option>Pending</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Activity','Type','Subject','Contact','Opportunity','Date','Owner','Status','Priority','Next Action','Reminder','Action'].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map(a=><tr key={a.id} className="hover:bg-slate-50/70"><td className="px-4 py-4 font-semibold text-slate-700">{a.id}</td><td className="px-4 py-4"><div className="flex items-center gap-2"><ActivityIcon type={a.activityType}/>{a.activityType}</div></td><td className="px-4 py-4"><p className="font-semibold text-slate-800">{a.subject}</p><p className="mt-1 max-w-[240px] text-xs text-slate-500">{a.description}</p></td><td className="px-4 py-4">{a.relatedContact}</td><td className="px-4 py-4">{a.relatedOpportunity}</td><td className="px-4 py-4 text-slate-500">{a.activityDate}</td><td className="px-4 py-4">{a.owner}</td><td className="px-4 py-4"><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${portalStatus(a.status)}`}>{a.status}</span></td><td className="px-4 py-4"><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${priorityBadge(a.priority)}`}>{a.priority}</span></td><td className="px-4 py-4 text-slate-600">{a.nextAction}</td><td className="px-4 py-4 font-medium">{a.reminderDate}</td><td className="px-4 py-4">{a.status!=='Completed'&&<button onClick={()=>setActivities(prev=>prev.map(x=>x.id===a.id?{...x,status:'Completed'}:x))} className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 bg-emerald-50 px-2.5 py-1.5 text-xs font-semibold text-emerald-700"><Check size={13}/> Complete</button>}</td></tr>)}</tbody></table></div></div>
 {showCreate&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={create} className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-blue-600">Customer Activity</p><h2 className="mt-1 text-xl font-bold">Log New Activity</h2></div><button type="button" onClick={()=>setShowCreate(false)} className="text-slate-400"><X size={19}/></button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Activity Type</span><select value={form.activityType} onChange={e=>setForm({...form,activityType:e.target.value as CustomerActivity['activityType']})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option>Call</option><option>Email</option><option>Meeting</option><option>Task</option><option>Note</option></select></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Priority</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Priority})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label><label className="block md:col-span-2"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Subject</span><input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="block md:col-span-2"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Description</span><textarea required rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Next Action</span><input value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-500">Reminder Date</span><input type="date" value={form.reminderDate} onChange={e=>setForm({...form,reminderDate:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowCreate(false)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Create Activity</button></div></form></div>}
 </div>;
};
