import React from 'react';
import { ArrowRight, Bell, CalendarClock, CheckCircle2, FileText, Headphones, Package, Plus, ShieldCheck, UserRound, ReceiptText, FileCheck2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { customerOrders, customerInvoices, customerQuotations } from '../types/data';
import { getSupportTickets } from '../services/supportStore';
import { getCustomerActivities, getCustomerNotifications } from '../services/portalStore';
import { PageHeader, PortalNav, QuickLink, StatCard, formatMoney, portalStatus } from '../components/PortalUi';

export const CustomerPortalPage: React.FC = () => {
  const tickets = getSupportTickets();
  const activities = getCustomerActivities();
  const notifications = getCustomerNotifications();
  const openTickets = tickets.filter(t => t.status !== 'Resolved');
  const unread = notifications.filter(n => !n.read);
  const reminders = activities.filter(a => a.status !== 'Completed');
  const outstanding = customerInvoices.reduce((sum, invoice) => sum + invoice.balanceDue, 0);
  return <div className="p-5 md:p-7">
    <PageHeader title="Customer Portal" description="A complete self-service workspace for support, orders, invoices, quotations, activities and account management." action={<Link to="/crm/customer-portal/support" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-700"><Plus size={16}/> New Support Request</Link>} />
    <PortalNav />
    <div className="mb-6 overflow-hidden rounded-2xl border border-blue-100 bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 p-6 text-white shadow-sm"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-semibold"><ShieldCheck size={14}/> Acme Industries · Customer Workspace</div><h2 className="text-2xl font-bold">Welcome back, Rohan</h2><p className="mt-1 max-w-2xl text-sm text-blue-100">Everything your team needs to manage the customer relationship from one secure portal.</p></div><div className="rounded-2xl bg-white/10 p-4 backdrop-blur"><p className="text-xs text-blue-100">Account status</p><p className="mt-1 text-lg font-bold">Active & supported</p><p className="mt-1 text-xs text-blue-100">Last portal activity: Today, 09:10 AM</p></div></div></div>
    <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Open Support" value={openTickets.length} icon={<Headphones size={19}/>} /><StatCard label="Orders" value={customerOrders.length} icon={<Package size={19}/>} tone="bg-cyan-50 text-cyan-600"/><StatCard label="Outstanding" value={formatMoney(outstanding)} icon={<ReceiptText size={19}/>} tone="bg-orange-50 text-orange-600"/><StatCard label="Quotes" value={customerQuotations.length} icon={<FileCheck2 size={19}/>} tone="bg-violet-50 text-violet-600"/><StatCard label="Unread Alerts" value={unread.length} icon={<Bell size={19}/>} tone="bg-rose-50 text-rose-600"/></div>
    <div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><QuickLink to="/crm/customer-portal/support" label="Support Requests" count={tickets.length} icon={<Headphones size={18}/>} /><QuickLink to="/crm/customer-portal/orders" label="Orders" count={customerOrders.length} icon={<Package size={18}/>} /><QuickLink to="/crm/customer-portal/invoices" label="Invoices" count={customerInvoices.length} icon={<FileText size={18}/>} /><QuickLink to="/crm/customer-portal/quotations" label="Quotations" count={customerQuotations.length} icon={<FileCheck2 size={18}/>} /><QuickLink to="/crm/customer-portal/activities" label="Activities & Reminders" count={activities.length} icon={<CalendarClock size={18}/>} /><QuickLink to="/crm/customer-portal/account" label="Account & Billing" icon={<ReceiptText size={18}/>} /><QuickLink to="/crm/customer-portal/profile" label="Customer Profile" icon={<UserRound size={18}/>} /><QuickLink to="/crm/customer-portal/notifications" label="Notifications" count={unread.length} icon={<Bell size={18}/>} /></div>
    <div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]">
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold text-slate-900">Recent Support Requests</h2><p className="mt-1 text-xs text-slate-500">Latest conversations and resolution progress</p></div><Link to="/crm/customer-portal/support" className="text-xs font-semibold text-blue-600">View all</Link></div><div className="divide-y divide-slate-100">{tickets.slice(0,4).map(t=><Link key={t.id} to={`/crm/customer-portal/support/${t.id}`} className="flex items-center gap-3 p-4 hover:bg-slate-50"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Headphones size={18}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="text-xs font-semibold text-blue-600">{t.ticketNumber}</span><span className={`rounded-full border px-2 py-0.5 text-[10px] font-semibold ${portalStatus(t.status)}`}>{t.status}</span></div><p className="mt-1 truncate text-sm font-semibold text-slate-800">{t.subject}</p><p className="mt-0.5 text-xs text-slate-400">{t.category} · Assigned to {t.assignedTo}</p></div><ArrowRight size={16} className="text-slate-300"/></Link>)}</div></section>
      <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-900">Upcoming Reminders</h2><p className="mt-1 text-xs text-slate-500">Next actions for your account</p></div><div className="space-y-3 p-4">{reminders.slice(0,3).map(a=><div key={a.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-start gap-3"><CalendarClock size={17} className="mt-0.5 text-violet-500"/><div><p className="text-sm font-semibold text-slate-800">{a.subject}</p><p className="mt-1 text-xs text-slate-500">{a.nextAction}</p><p className="mt-2 text-[11px] font-semibold text-violet-600">Reminder · {a.reminderDate}</p></div></div></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Recent Account Activity</h2><div className="mt-3 space-y-3">{customerInvoices.slice(0,3).map(invoice => <Link key={invoice.id} to="/crm/customer-portal/invoices" className="flex items-center justify-between rounded-xl bg-slate-50 p-3 hover:bg-blue-50"><div><p className="text-xs font-semibold text-slate-800">{invoice.invoiceNumber}</p><p className="text-[11px] text-slate-500">Due {invoice.dueDate}</p></div><div className="text-right"><p className="text-xs font-bold text-slate-800">{formatMoney(invoice.total)}</p><span className={`text-[10px] font-semibold ${portalStatus(invoice.status)} rounded-full border px-2 py-0.5`}>{invoice.status}</span></div></Link>)}</div></section></div>
    </div>
  </div>;
};
export default CustomerPortalPage;
