import React, { useState } from 'react';
import { ArrowLeft, Download, FileText, MessageCircle, Paperclip, Send, UserRound } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getSupportTickets, saveSupportTickets } from '../services/supportStore';
import { DetailRow, PageHeader, PortalNav, portalStatus, priorityBadge } from '../components/PortalUi';

export const SupportDetailsPage: React.FC = () => {
  const { id } = useParams(); const navigate=useNavigate(); const [tickets,setTickets]=useState(getSupportTickets()); const [reply,setReply]=useState('');
  const ticket=tickets.find(t=>t.id===id);
  if(!ticket) return <div className="p-7"><PageHeader title="Support Request Not Found" description="The support request does not exist in the current customer portal data." action={<Link to="/crm/customer-portal/support" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Back to Requests</Link>}/><PortalNav/></div>;
  const sendReply=()=>{if(!reply.trim())return;const now=new Date().toLocaleString('en-IN',{month:'short',day:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});const updated=tickets.map(t=>t.id===ticket.id?{...t,updatedDate:now,conversation:[...t.conversation,{id:`c-${Date.now()}`,author:'Rohan Mehta',role:'Customer' as const,message:reply.trim(),date:now}]}:t);setTickets(updated);saveSupportTickets(updated);setReply('');};
  const downloadAttachment=(name:string)=>{const blob=new Blob([`Attachment placeholder for ${name}\nTicket: ${ticket.ticketNumber}`],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name.includes('.')?name:`${name}.txt`;a.click();URL.revokeObjectURL(url)};
  return <div className="p-5 md:p-7"><PageHeader title="Support Details" description={`${ticket.ticketNumber} · Full ticket history, attachments and resolution information.`} action={<Link to="/crm/customer-portal/support" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-blue-200 hover:text-blue-600"><ArrowLeft size={17}/> Back to Requests</Link>}/><PortalNav/>
    <div className="mb-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-xs font-semibold text-blue-600">{ticket.ticketNumber}</div><h2 className="mt-1 text-xl font-bold text-slate-900">{ticket.subject}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{ticket.description}</p></div><div className="flex gap-2"><span className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${priorityBadge(ticket.priority)}`}>{ticket.priority} Priority</span><span className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${portalStatus(ticket.status)}`}>{ticket.status}</span></div></div></div>
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-[1fr_360px]"><div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h3 className="flex items-center gap-2 font-bold text-slate-900"><MessageCircle size={18} className="text-blue-600"/> Conversation History</h3></div><div className="space-y-5 p-5">{ticket.conversation.map(c=><div key={c.id} className="flex gap-3"><div className={`mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${c.role==='Support'?'bg-blue-100 text-blue-700':'bg-slate-100 text-slate-600'}`}><UserRound size={17}/></div><div className="flex-1 rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="text-sm font-semibold text-slate-900">{c.author}</span><span className="ml-2 text-xs text-slate-400">{c.role}</span></div><span className="text-xs text-slate-400">{c.date}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{c.message}</p></div></div>)}</div><div className="border-t border-slate-100 p-4"><div className="flex flex-col gap-2 sm:flex-row"><input value={reply} onChange={e=>setReply(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendReply()}}} placeholder="Write a reply..." className="flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100"/><button onClick={sendReply} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><Send size={16}/> Send</button></div><p className="mt-2 text-[11px] text-slate-400">Replies are saved to this browser's local demo data.</p></div></section><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h3 className="font-bold text-slate-900">Resolution Notes</h3></div><div className="p-5 text-sm leading-6 text-slate-600">{ticket.resolutionNotes}</div></section></div>
      <aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="mb-3 font-bold text-slate-900">Ticket Information</h3><dl><DetailRow label="Ticket ID" value={ticket.id}/><DetailRow label="Ticket Number" value={ticket.ticketNumber}/><DetailRow label="Category" value={ticket.category}/><DetailRow label="Customer" value={ticket.customer}/><DetailRow label="Contact" value={ticket.contact}/><DetailRow label="Assigned To" value={ticket.assignedTo}/><DetailRow label="Status" value={<span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${portalStatus(ticket.status)}`}>{ticket.status}</span>}/><DetailRow label="Created Date" value={ticket.createdDate}/><DetailRow label="Updated Date" value={ticket.updatedDate}/><DetailRow label="Expected Resolution Date" value={ticket.expectedResolutionDate}/></dl></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="mb-4 flex items-center gap-2 font-bold text-slate-900"><Paperclip size={18} className="text-blue-600"/> Attachments</h3>{ticket.attachments.length?<div className="space-y-2">{ticket.attachments.map(a=><div key={a.name} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-500"><FileText size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{a.name}</p><p className="text-xs text-slate-400">{a.size}</p></div><button onClick={()=>downloadAttachment(a.name)} className="text-slate-400 hover:text-blue-600" title="Download"><Download size={16}/></button></div>)}</div>:<p className="text-sm text-slate-500">No attachments.</p>}</section></aside></div>
  </div>;
};
